CREATE TABLE Users (
  UserId INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
  Phone INT DEFAULT NULL,
  Address VARCHAR(255) DEFAULT NULL
);

CREATE TABLE Category (
  CategoryId INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL
);

CREATE TABLE Size (
  SizeId INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL
);

CREATE TABLE Config (
  ConfigId INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Value VARCHAR(255) NOT NULL
);

CREATE TABLE PaymentMethod (
  PaymentMethodId INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Value VARCHAR(255) NOT NULL
);

CREATE TABLE ShippingMethod (
  ShippingMethodId INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Value VARCHAR(255) NOT NULL
);

CREATE TABLE Promotion (
  PromotionId INT PRIMARY KEY AUTO_INCREMENT,
  Code VARCHAR(255) NOT NULL,
  IsActive BOOLEAN DEFAULT TRUE,
  Discount INT DEFAULT 0
);

CREATE TABLE Product (
  ProductId INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  CategoryId INT,
  Price DECIMAL,
  Discount INT DEFAULT 0,
  UrlPhoto VARCHAR(255) DEFAULT NULL,
  IsActive BOOLEAN DEFAULT TRUE,
  FOREIGN KEY (CategoryId) REFERENCES Category(CategoryId)
);

CREATE TABLE ShoppingCart (
  CartId INT PRIMARY KEY AUTO_INCREMENT,
  UserId INT,
  DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
  DateUpdated DATETIME DEFAULT CURRENT_TIMESTAMP,
  IsFinish BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (UserId) REFERENCES Users(UserId)
);

CREATE TABLE CartItems (
  CartItemId INT PRIMARY KEY AUTO_INCREMENT,
  CartId INT,
  VariantId INT,
  Quantity INT NOT NULL,
  UnitPrice DECIMAL NOT NULL,
  TotalPrice DECIMAL NOT NULL,
  DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
  DateUpdated DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (CartId) REFERENCES ShoppingCart(CartId),
  FOREIGN KEY (VariantId) REFERENCES Variant(VariantId)
);

CREATE TABLE OrderStatus (
  OrderStatusId INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL
);

CREATE TABLE Orders (
  OrderId INT PRIMARY KEY AUTO_INCREMENT,
  OrderNumber VARCHAR(255) NOT NULL,
  DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
  OrderStatusId INT NOT NULL,
  UserId INT NOT NULL,
  Total DECIMAL,
  PromotionId INT,
  PaymentMethodId INT,
  ShippingMethodId INT,
  IsActive BOOLEAN DEFAULT TRUE,
  FOREIGN KEY (OrderStatusId) REFERENCES OrderStatus(OrderStatusId),
  FOREIGN KEY (UserId) REFERENCES Users(UserId),
  FOREIGN KEY (PromotionId) REFERENCES Promotion(PromotionId),
  FOREIGN KEY (PaymentMethodId) REFERENCES PaymentMethod(PaymentMethodId),
  FOREIGN KEY (ShippingMethodId) REFERENCES ShippingMethod(ShippingMethodId)
);

CREATE TABLE Variant (
  VariantId INT PRIMARY KEY AUTO_INCREMENT,
  ProductId INT,
  SizeId INT,
  Stock INT NOT NULL,
  FOREIGN KEY (ProductId) REFERENCES Product(ProductId),
  FOREIGN KEY (SizeId) REFERENCES Size(SizeId)
);

CREATE TABLE OrderItems (
  OrderItemId INT PRIMARY KEY AUTO_INCREMENT,
  VariantId INT,
  Quantity INT NOT NULL,
  UnitPrice DECIMAL NOT NULL,
  TotalPrice DECIMAL NOT NULL,
  DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
  DateUpdated DATETIME DEFAULT CURRENT_TIMESTAMP,
  OrderId INT NOT NULL,
  FOREIGN KEY (VariantId) REFERENCES Variant(VariantId),
  FOREIGN KEY (OrderId) REFERENCES Orders(OrderId)
);
