### Get all products, se puede filtrar por Name, Category y Status a traves de query params, se tiene que pasar paginación (todos opcionales)
GET http://localhost:3002/api/v1/products?name=&categories=&status=&page=&limit=2
Accept: application/json

### Obtener todos los productos promocionales, sin filtros ni paginación
GET http://localhost:3002/api/v1/products/promotional
Accept: application/json

### Obtener listado de todos los productos activos, se puede filtrar por nombre, categorias o talles. Se tiene que enviar paginación
GET http://localhost:3002/api/v1/products/pagedList?name=&categories=pantalon&sizes=&page=&limit=
Accept: application/json

### Obtener producto por id, pasar el id por query params
GET http://localhost:3002/api/v1/products/product?id=3
Accept: application/json


### Cambiar de estado un producto, hay que pasarle el id y el status en el body
PUT http://localhost:3002/api/v1/products/product
Accept: application/json
Authorization: token xxx
Content-Type: application/json

{
    "id": 3,
    "status": "active"
}

### Crear producto
POST http://localhost:3002/api/v1/products
Accept: application/json
Authorization: token xxx
Content-Type: application/json

{
    "Name": "Remera manga corta",
    "Price": 2000,
    "Cost": 1000,
    "Description": "Remera manga corta de algodon",
    "CategoryId": 2
}

### Obtener la lista de precios
GET http://localhost:3002/api/v1/products/priceList?category=2
Accept: application/json

### Cambiar el precio y descuento de un producto de manera individual.
POST http://localhost:3002/api/v1/products/updatePrice
Accept: application/json
Authorization: token xxx
Content-Type: application/json

{
    "productId": 1,
    "price": 7000,
    "discount": 15
}